name: Scheduled Cronjob

on:
  schedule:
    # Runs every day at midnight
    - cron: '*/10 * * * *'
    # Example: Runs every 10 minutes
    # - cron: '*/10 * * * *'

jobs:
  cronjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          echo "Running Cronjob!"
          curl -s https://api.kimcv.com/v1/signal?symbol=BTCUSDT&alert=1
